In [1]:
import numpy as np

In [2]:
arr=[int(i) for i in input().split()]
arr=np.array(arr)
arr

4 5 6 7 8


array([4, 5, 6, 7, 8])

In [3]:
print(np.__version__)

1.16.2


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
#tuple to create array
arr=np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [6]:
#create a 0-D array
a=np.array(10)
a

array(10)

In [7]:
#create a 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
#create a 3-D array
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1dim 4


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [16]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
